In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import tree

In [22]:
df = pd.read_csv("titanic.csv")
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [25]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [26]:
inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [27]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [28]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [29]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [30]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [31]:
len(X_train)

712

In [32]:
len(X_test)

179

In [33]:
model = tree.DecisionTreeClassifier()

In [34]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [35]:
model.score(X_test,y_test)

0.7877094972067039